### ISSUE TITLE
Some services are not able to be constructed

### ISSUE THREAD

**Issue by HenriqueFon** [lucamesquitaa/EcommerceAPI#1]
O problema está acontecendo porque o seu builder não está conseguindo localizar uma instância válida do seu dbContext (Scoped ImplementationType: EcommerceAPI.Data.ApiContext': A suitable constructor for type 'EcommerceAPI.Data.ApiContext' could not be located. ). Isso acontece porque no seu context você o definiu como protected e por isso como o seu program não herda o mesmo, ele acaba por não utilizar. Trocar o tipo para public irá resolver o problema.

public class ApiContext : DbContext
    {
        public ApiContext(DbContextOptions<ApiContext> options) : base(options)
        {
            Database.EnsureCreated();
        }
        public DbSet<Products> ProductsDb { get; set; }
    }

**Comment by lucamesquitaa** [comment]
Entendi, obrigado.
